server:
  port: 9999
spring:
  application:
    name: auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.12:8848
  datasource:
    username: root
    password: 123456root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sso?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 192.168.2.12
    port: 6379